Make buildabuild with Ruby 2.4+ and MSYS2's gcc
Because Ruby 2.4 or later depends on MSYS2, and MSYS2 recently uses
fortiled functions by default.
We should adopt this change on omnibus-td-agent because Ruby 2.3
had been marked as EOL in the previous year.
So, we should migrate building process on Windows to use Ruby 2.4+.

Otherwise, without this change, omnibus-td-agent complains the following error
with Ruby 2.4+ and MSYS2:

```log
Error:

    C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: array.o:array.c:(.text+0xa9f4): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bignum.o:bignum.c:(.text+0xa8e7): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: io.o:io.c:(.text+0xa5b): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: numeric.o:numeric.c:(.text+0x2ae5): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: numeric.o:numeric.c:(.text+0x2c98): undefined reference to `__memmove_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: regerror.o:regerror.c:(.text+0x32b): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: sprintf.o:sprintf.c:(.text+0x1de2): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: string.o:string.c:(.text+0x4182): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: string.o:string.c:(.text+0x4236): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: string.o:string.c:(.text+0x429f): undefined reference to `__memcpy_chk'
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: string.o:string.c:(.text+0x4300): more undefined references to `__memcpy_chk' follow
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:224: miniruby.exe] エラー 1
```

See also: https://github.com/msys2/MINGW-packages/issues/5803

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>